name: Build Library
on:
  push:
    branches:
      - master

jobs:
  test:
    name: Run unit tests
    runs_on: ubuntu-latest
    strategy:
      matrix:
        node: [ 12, 10 ]
      name: Node ${{ matrix.node }} sample
      steps:
        - uses: actions/checkout@v1
        - name: Setup node
          uses: actions/setup-node@v1
          with:
            node-version: ${{ matrix.node }}
        - run: npm install
        - run: npm test

#  build:
#    name: Build package
#    needs: test
#    runs_on: ubuntu-latest
#  deploy:
#    name: Deploy to npm registry
#    needs: [test, build]
#    runs_on: ubuntu-latest

