name: Demo pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy demo app to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Commit to repository
        run: |
          git config --global user.name ${{secrets.GITHUB_ACTOR}}
          git config --global user.email ${{secrets.GITHUB_ACTOR_MAIL}}

          git subtree add --prefix dist/${{secrets.GITHUB_DEMO_DIST}} origin gh-pages
          git add dist/${{secrets.GITHUB_DEMO_DIST}} -f
          git commit -m "${{ steps.get_version.outputs.VERSION }} demo release"
          git subtree push --prefix dist/${{secrets.GITHUB_DEMO_DIST}} origin gh-pages
