name: Demo pages

on:
  push:
    tags:
      - v*

jobs:
  deploy:
    name: Deploy demo app to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Set subtree
        env:
          USER: ${{ secrets.USER }}
          EMAIL: ${{ secrets.EMAIL }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $EMAIL

          git subtree add --prefix dist/ngx-group-validator-demo https://github.com/${GITHUB_REPOSITORY}.git gh-pages
      - name: Build demo
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: |
          npm install
          npm run build:demo
      - name: Deploy to repo
        uses: actions/checkout@v1
      - run: |
          git add dist/ngx-group-validator-demo -f
          git commit -m "demo release"
          git subtree push --prefix dist/ngx-group-validator-demo https://${TOKEN}@github.com/${GITHUB_REPOSITORY}.git gh-pages
