name: Demo pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy demo app to gh-pages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - name: Print a greeting
        env:
          MY_VAR: Hi there! My name is
          FIRST_NAME: Mona
          MIDDLE_NAME: The
          LAST_NAME: Octocat
        run: |
          echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      - name: Commit to repository
        env:
          mail: blazej456@gmail.com
          dist_dir: ngx-group-validator-demo
        run: |
          echo $GITHUB_ACTOR
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $mail

          git subtree add --prefix dist/$dist_dir origin gh-pages
          git add dist/$dist_dir -f
          git commit -m "demo release"
          git subtree push --prefix dist/$dist_dir origin gh-pages
