name: Test and Bump version

on:
  push:
    branch:
      - master

jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Copying repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install deps
        run: yarn install
      - name: Run tests
        run: yarn test

  bump:
    name: Bump version
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Copying repository
        uses: actions/checkout@v2
        with:
          fetch-depth: '0'
      - name: Produce new tag
        uses: anothrNick/github-tag-action@1.17.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DRY_RUN: true
          DEFAULT_BUMP: patch
      - name: Bump version
        env:
          NEW_TAG: ${{ env.new_tag }}
        run: npm version $NEW_TAG
      - name: Push tag
        env:
          USER: ${{ secrets.USER }}
          EMAIL: ${{ secrets.EMAIL }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name $GITHUB_ACTOR
          git config --global user.email $EMAIL

          git push --follow-tags https://${TOKEN}@github.com/${GITHUB_REPOSITORY}.git origin master

  build:
    name: Build library
    needs: bump
    runs-on: ubuntu-latest
    steps:
      - name: Copying repository
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - name: Install deps
        run: yarn install
      - name: Build
        run: yarn build
      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
        run: |
          cd dist/ngx-group-validator
          npm publish
